services:
  backend:
    build:
      context: ./backend
    networks:
      - dev

  frontend:
    build:
      context: ./frontend
    networks:
      - dev
  # nginx:
  #   image: nginx:stable-alpine
  #   ports:
  #     - "80:80"
  #   volumes:
  #     - "./nginx.conf:/etc/nginx/nginx.conf"
  #   depends_on:
  #     - backend
  #     - frontend
  #   networks:
  #     - dev

  nginx:
    image: nginx:stable-alpine
    container_name: felix-portfolio-nginx
    volumes:
      - "./nginx_subdomain.conf:/etc/nginx/nginx.conf"
      - "./letsencrypt:/etc/letsencrypt"
      - "./certbot:/var/www/certbot"
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - frontend
      - backend
    networks:
      - dev
    restart: unless-stopped

  certbot:
    image: certbot/certbot
    volumes:
      - "./letsencrypt:/etc/letsencrypt"
      - "./certbot:/var/www/certbot"
    entrypoint: /bin/sh -c "trap exit TERM; while :; do certbot renew --deploy-hook 'docker exec felix-portfolio-nginx nginx -s reload'; sleep 168h & wait $${!}; done"
    depends_on:
      - nginx    
    networks:
      - dev

networks:
  dev:
